services:
  nginx:
    container_name: mongo-nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: mongo-php
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini

  mongo:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example